from .grok_vision_node import (
    NODE_CLASS_MAPPINGS as _MAPPINGS_VISION,
    NODE_DISPLAY_NAME_MAPPINGS as _NAMES_VISION,
)
from .grok_text_prompt import (
    NODE_CLASS_MAPPINGS as _MAPPINGS_KREA2,
    NODE_DISPLAY_NAME_MAPPINGS as _NAMES_KREA2,
)

# Fusionar ambos diccionarios
NODE_CLASS_MAPPINGS = {**_MAPPINGS_VISION, **_MAPPINGS_KREA2}
NODE_DISPLAY_NAME_MAPPINGS = {**_NAMES_VISION, **_NAMES_KREA2}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
